# Generated by Django 2.2.11 on 2020-03-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='dfg',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='fvfg',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
